
  create table "public"."elicit_messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "conversation_id" uuid not null default gen_random_uuid(),
    "message_id" uuid not null default gen_random_uuid(),
    "user_id" uuid default auth.uid(),
    "content" text not null,
    "role" character varying not null,
    "type" smallint not null
      );


alter table "public"."elicit_messages" enable row level security;

CREATE UNIQUE INDEX elicit_messages_pkey ON public.elicit_messages USING btree (id);

alter table "public"."elicit_messages" add constraint "elicit_messages_pkey" PRIMARY KEY using index "elicit_messages_pkey";

alter table "public"."elicit_messages" add constraint "elicit_messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES public.elicit_conversations(conversation_id) not valid;

alter table "public"."elicit_messages" validate constraint "elicit_messages_conversation_id_fkey";

grant delete on table "public"."elicit_messages" to "anon";

grant insert on table "public"."elicit_messages" to "anon";

grant references on table "public"."elicit_messages" to "anon";

grant select on table "public"."elicit_messages" to "anon";

grant trigger on table "public"."elicit_messages" to "anon";

grant truncate on table "public"."elicit_messages" to "anon";

grant update on table "public"."elicit_messages" to "anon";

grant delete on table "public"."elicit_messages" to "authenticated";

grant insert on table "public"."elicit_messages" to "authenticated";

grant references on table "public"."elicit_messages" to "authenticated";

grant select on table "public"."elicit_messages" to "authenticated";

grant trigger on table "public"."elicit_messages" to "authenticated";

grant truncate on table "public"."elicit_messages" to "authenticated";

grant update on table "public"."elicit_messages" to "authenticated";

grant delete on table "public"."elicit_messages" to "postgres";

grant insert on table "public"."elicit_messages" to "postgres";

grant references on table "public"."elicit_messages" to "postgres";

grant select on table "public"."elicit_messages" to "postgres";

grant trigger on table "public"."elicit_messages" to "postgres";

grant truncate on table "public"."elicit_messages" to "postgres";

grant update on table "public"."elicit_messages" to "postgres";

grant delete on table "public"."elicit_messages" to "service_role";

grant insert on table "public"."elicit_messages" to "service_role";

grant references on table "public"."elicit_messages" to "service_role";

grant select on table "public"."elicit_messages" to "service_role";

grant trigger on table "public"."elicit_messages" to "service_role";

grant truncate on table "public"."elicit_messages" to "service_role";

grant update on table "public"."elicit_messages" to "service_role";


  create policy "elicit_message_insert_own"
  on "public"."elicit_messages"
  as permissive
  for insert
  to authenticator
with check ((user_id = auth.uid()));



  create policy "elicit_messages_delete_own"
  on "public"."elicit_messages"
  as permissive
  for delete
  to public
using ((user_id = auth.uid()));



  create policy "elicit_messages_select_own"
  on "public"."elicit_messages"
  as permissive
  for select
  to public
using ((user_id = auth.uid()));



  create policy "elicit_messages_update_own"
  on "public"."elicit_messages"
  as permissive
  for update
  to authenticator
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));



